language: python

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/lektor/builds

python:
  - '3.6'

jobs:
  include:
    - stage: Run Tests
      install:
        - pip install flake8
        - pip install nose
        - pip install -r REQUIREMENTS.txt
      script:
        - nosetests -w tests/
        - flake8 bolt/

    - stage: Build Artifacts
      install:
        - apt-get install python3.6-dev libxml2-dev libxslt-dev
        - pip install bumpversion
        - pip install pyinstaller
        - pip install -r REQUIREMENTS.txt
      script:
        - bumpversion patch --allow-dirty
        - pyinstaller --onefile -n bolt entrypoint.py
        - mv dist/bolt pkg/usr/bin/bolt
        - pushd pkg/
        - tar -czf bolt-0.3.2.tar.gz *
        - popd

    - stage: Build Docs
      install:
        - pip install lektor
        - gem install sass
      script:
        - scss --style=compressed docs/scss/milligram.scss > docs/assets/static/milligram.min.css
        - pushd docs && lektor build && popd
      deploy:
        provider: script
        script: "cd docs && lektor deploy ghpages"
        on:
          branch: master

stages:
  - name: Run Tests
  - name: Build Artifacts
  - name: Build Docs
    if: branch = master
