language: python

dist: xenial

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/lektor/builds

python:
  - '3.6'

jobs:
  include:
    - stage: Run Tests
      install:
        - pip install flake8
        - pip install nose
        - pip install -r REQUIREMENTS.txt
      script:
        - nosetests -w tests/
        - flake8 bolt/

    - stage: Build Artifacts
      install:
        - sudo apt-get install libxml2-dev libxslt-dev
        - pip install bumpversion
        - pip install pyinstaller
        - pip install -r REQUIREMENTS.txt
      script:
        - pyinstaller --onefile -n bolt entrypoint.py
        - mv dist/bolt pkg/usr/bin/bolt
        - pushd pkg/
        - tar -czf bolt-installer.tar.gz *
        - mv bolt-installer.tar.gz ..
        - popd
      deploy:
        provider: releases
        api_key:
          secure: EK+NEDqmU5saU+yUdDpeQrSy6k5XIJiDU2ppYwW/5QvcsY4fwEzpAY+NaoD79JxuW1CjuFfSt7LgW+gg0bWNNzI8HnCaU0v64L0n4alChZtEU14BXQxX+YpUEqiQDgnvCs+SaK3xsOhbqxfVosVwTWMtsEyR17kfX1sF4rgtabc=
        file: "bolt-installer.tar.gz"
        prerelease: true
        on:
          tags: true

    - stage: Build Docs
      install:
        - pip install lektor
        - gem install sass
      script:
        - scss --style=compressed docs/scss/milligram.scss > docs/assets/static/milligram.min.css
        - pushd docs && lektor build && popd
      deploy:
        provider: script
        script: "cd docs && lektor deploy ghpages"
        on:
          branch: master

stages:
  - name: Run Tests
  - name: Build Artifacts
  - name: Build Docs
    if: branch = master
