language: python

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/lektor/builds

python:
  - '3.6'

jobs:
  include:
    - stage: Run Tests
      install:
        - pip install flake8
        - pip install nose
      script:
        - pip install -r REQUIREMENTS.txt
        - nosetests -w tests/
        - flake8 bolt/

    - stage: Build Artifacts
      install:
        - pip install pyinstaller

    - stage: Bump Version
      install:
        - pip install bumpversion
      script:
        - bumpversion patch --allow-dirty

    - stage: Build Docs
      install:
        - pip install lektor
        - gem install sass
      script:
        - scss --style=compressed docs/scss/milligram.scss > docs/assets/static/milligram.min.css
        - pushd docs && lektor build && popd
      deploy:
        provider: script
        script: "cd docs && lektor deploy ghpages"
        on:
          branch: master

stages:
  - name: Run Tests
  - name: Build Artifacts
  - name: Bump Version
    if: branch = master
  - name: Build Docs
    if: branch = master
