# -----------------------------------------------------------------------------
# Bolt v0.6.2
#
# Author: Patrick Hennessy
# Source Code: https://github.com/ns-phennessy/Bolt
# License: MIT
# -----------------------------------------------------------------------------
---

# General
# -----------------------------------------------------------------------------
# Discord API key used to connect to the websocket and use the Discord API
# https://discordapp.com/developers/applications/
api_key: "Mzk5NDU4Mjg0NzY5Mzc4MzA5.XVZQzg.uIjA_DHxVxLqz5pAmJn8IJ45mrw"

# Bot will refer to itself by this name
# Some plugins may set the bot's name to this
name: "Ms. Pauling"

# Trigger is used as the default prefix for invoking commands
# Some plugins may choose to override this value
trigger: "!"

# Amount of Green threads for the bot to spin up
# These are extremely light threads so high numbers are okay
# This allows for N amount of concurrent work to be performed by the bot
worker_threads: 25

# Sharding
# -----------------------------------------------------------------------------
# https://discordapp.com/developers/docs/topics/gateway#sharding
shard_total: 1      # Total number of shards to distribute to
shard_id: 0         # Shard number for this node

# Database Credentials
# -----------------------------------------------------------------------------
mongo_database_uri: "mongodb://localhost:27017"
mongo_database_username: ""
mongo_database_password: ""
mongo_database_use_tls: false

# Webhook
# -----------------------------------------------------------------------------
webhook_enable: true
webhook_port: 8080

# Plugins
# -----------------------------------------------------------------------------
plugin_dir: /etc/bolt/plugins.enabled.d/

# Logging
# -----------------------------------------------------------------------------
log_level: DEBUG        # Must be one of: DEBUG, INFO, WARNING, ERROR, CRITICAL
log_dir: /var/log/bolt/

# Backdoor Server
# -----------------------------------------------------------------------------
# http://www.gevent.org/api/gevent.backdoor.html
# Backdoor server creates a TCP server you can telnet to a gain access to the
# bot. The server exposes a 'bot' local variable.
backdoor_enable: true
backdoor_host: 127.0.0.1
backdoor_port: 5000

# Plugin specific
# -----------------------------------------------------------------------------
plugins:
    RBAC:
        owners:
          - "65497519504764928" # Zeus
          - "256559833803784194"
          - "143877973156560897"
          - "134078616727322625"
          - "96272905167446016" # Calculon
        roles:
            pug_admin:
            - Pugs.*
            - ServeMe.*
            default:
            - Manage.*
            - LogsTF.*
            - DemosTF.*
            - Steam.*
            - UrbanDictionary.*
            - Help.*
            - Chance.*
            - Inspire.*
    Status:
        statuses:
        - Team Fortress 2
        - Team Fort Defense
        - Hat Simulator
        - Scream Fortress 2
        - type "!help" for commands
